apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
    ENVIRONMENT: "DEV"
    HOST: "localhost" 
    PORT: "8000"
    REDIS_HOST: "redisexten1"
    REDIS_PORT: "6379"
    REDIS_DB: "0"