apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pythonapp.fullname" . }}
  labels:
    {{- include "pythonapp.selectorLabels" . | nindent 8 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pythonapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pythonapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef: 
           name: {{ .Values.configMap.name }}